markdown:         kramdown
gems:             [jekyll-paginate]
highlighter:      rouge
paginate:         4

title:            BenHeart's Blog
url:              https://benheart.github.io/
author:
    name:         BenHeart
    email:        geek.hu@qq.com
description:      "Ben's blog -- A place to record my study, work and life."
about: 			  "A graduate from HIT, attention to the network programming, website development, data mining."

style: 			  /css/style.css
feed:             /atom.xml
blogName: 		  BenHeart
blogDesc: 		  Coder & Geeker

follow:
    github:       https://github.com/benheart
    facebook:     https://www.facebook.com/wenjun.hu.792