markdown:         kramdown
gems:             [jekyll-paginate]
highlighter:      rouge
paginate:         5
comments:         true

title:            BenHeart's Blog
url:              https://benheart.github.io/
description:      "Ben's blog -- A place to record my study, work and life."
author:
    name:         BenHeart
    email:        geek.hu@qq.com
    about:        "A graduate from HIT, attention to the Network Programming, Website Development, Data Mining."

style: 			  /css/style.css
feed:             /atom.xml
blogName: 		  BenHeart
blogDesc: 		  Coder & Geeker

follow:
    github:       https://github.com/benheart
    zhihu:        https://www.zhihu.com/people/benheart
    facebook:     https://www.facebook.com/benheart.hu
    linkedin:     https://www.linkedin.com/in/benheart